### ISSUE TITLE
Crash when minimizing and opening the app again

### ISSUE THREAD

**Issue by philipgiuliani** [boxme/SquareCamera#10]
Steps to reproduce:

* Open the camera (Demo app also)
* Go to homescreen
* Switch back to the App
* Camera is black. Click on it and it crashes.

**Comment by oZarya** [comment]
Same issue, quite annoying. Except that, great library, thanks a lot btw :)

**Comment by boxme** [comment]
Resolved in f135f2a99f374e66b6d8f21bd7d1ee09610df894
