### ISSUE TITLE
Clicked Image Save issue

### ISSUE THREAD

**Issue by techmightyaj** [boxme/SquareCamera#14]
The uri get null reference when we click the image we get a null reference.

**Comment by philipgiuliani** [comment]
Have you added the WRITE_EXTERNAL_STORAGE permission?

**Comment by techmightyaj** [comment]
Oops!! Sorry i Forgot That. Thank you.

**Comment by philipgiuliani** [comment]
No problem, maybe we should add that to the README. Its not mentioned there.
