### ISSUE TITLE
Where is the code that makes the preview area square?

### ISSUE THREAD

**Issue by chriszeng87** [boxme/SquareCamera#15]
This is not a bug issue. I'm just wondering where is the code that makes the preview area square? I debug for a while and no progress? Besides, in CameraFragment's determineBestSize method, why you make desire ratio to like this:
boolean isDesireRatio = (size.width / 4) == (size.height / 3);
Thank you.

**Comment by philipgiuliani** [comment]
The camera isn't really a square. He is just overlaying it with black
covers that it seems like a square.
Aspectratio of 4/3 is supported by every camera. So he is taking that to
know how large the covers should be.

chriszeng87 <notifications@github.com> schrieb am Fr., 24. Juli 2015 08:09:

> This is not a bug issue. I'm just wondering where is the code that makes
> the preview area square? I debug for a while and no progress? Besides, in
> CameraFragment's determineBestSize method, why you make desire ratio to
> like this:
> boolean isDesireRatio = (size.width / 4) == (size.height / 3);
> Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/boxme/SquareCamera/issues/15>.
>
-- 
Mit freundlichen Grüßen
Philip Giuliani

**Comment by chriszeng87** [comment]
Thank you for answered my question so soon! Got it, cover_bottom_view is used to cover the extra area to 'make' the preview area seemed square:)

**Comment by philipgiuliani** [comment]
You're welcome. Maybe close the issue when you have no other questions :+1:
