### ISSUE TITLE
black screen until I change flash mode

### ISSUE THREAD

**Issue by IlyaEremin** [boxme/SquareCamera#19]
I run camera and see black square instead of camera output. When I click on flash mode then camera work fine.
I use xperia Z1 compact phone with 5.0 on the board.

**Comment by tier777** [comment]
Same problem on Nexus 5

**Comment by IlyaEremin** [comment]
Seems like https://github.com/boxme/SquareCamera/commit/d728623c437b6284d139b278015118604f7803d8 fix this issue.

**Comment by boxme** [comment]
@IlyaEremin does d728623c437b6284d139b278015118604f7803d8 fix the issue for you?

**Comment by boxme** [comment]
@IlyaEremin @tier777 If the issue remains, check out the latest commit c4edc3e3ac4b6efaf472c6be0e55cf9a0098ec1a. Check if the demo in this library is working fine on your test devices.

**Comment by IlyaEremin** [comment]
@boxme https://github.com/boxme/SquareCamera/commit/c4edc3e3ac4b6efaf472c6be0e55cf9a0098ec1a is just refactor, it does not affect on camera behavior.
Yes, https://github.com/boxme/SquareCamera/commit/d728623c437b6284d139b278015118604f7803d8 fix this issue on my device
