### ISSUE TITLE
Preview not squared on galaxy tab 3

### ISSUE THREAD

**Issue by GiacomoDB** [boxme/SquareCamera#21]
This is how the preview looks like on Samsung galaxy tab 3:
![bug](https://cloud.githubusercontent.com/assets/8988591/9379523/e3a8304e-4721-11e5-8ee8-dd2a2d521084.png)
I did't check the code yet, someone have notice this issue before? The picture taken is squared and perfectly good, it's just a problem with the size of the preview.

**Comment by GiacomoDB** [comment]
As I have seen so for It depends from the dimensions:

<dimen name="squarecamera__cover_start_height">xxxdp</dimen>
<dimen name="squarecamera__cover_start_width">xxxdp</dimen>

Any clue about this?

**Comment by boxme** [comment]
@GiacomoDB Check out the latest commit c4edc3e3ac4b6efaf472c6be0e55cf9a0098ec1a. Check if the demo in this library is working fine on your test devices.

**Comment by GiacomoDB** [comment]
Solved! work like a charm. The animation fix the preview.
