### ISSUE TITLE
Showing camera has problem

### ISSUE THREAD

**Issue by alirezaaa** [boxme/SquareCamera#23]
Hi,

I've used your library and everything is fine, thanks, but showing the camera section is the only problem which is exists. The camera section not showing or sometimes showing. How can I fix this important problem?

**Comment by boxme** [comment]
Are you using the latest version 1.0.3? What phone are you using for this? In addition, does the camera preview not show all the time?

**Comment by alirezaaa** [comment]
Yes, I've imported the latest version and I tested it on the emulator Android 5.1 and my device (HTC One X with custom ROM Android 5.1). just one time shown but now every times not showing.

**Comment by boxme** [comment]
@alirezaaa Check out c4edc3e3ac4b6efaf472c6be0e55cf9a0098ec1a. Clone this project and check if the demo is working fine with your test devices.

**Comment by boxme** [comment]
Issue is resolved in d728623c437b6284d139b278015118604f7803d8
