### ISSUE TITLE
Theme problem

### ISSUE THREAD

**Issue by jdsepulveda** [boxme/SquareCamera#42]
I'm getting this error when I try to build the project using this library:
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@theme value=(@style/AppTheme) from AndroidManifest.xml:16:9-40
    is also present at [com.github.boxme:squarecamera:1.1.0] AndroidManifest.xml:11:18-76 value=(@style/squarecamera__CameraFullScreenTheme).
    Suggestion: add 'tools:replace="android:theme"' to <application> element at AndroidManifest.xml:11:5-57:19 to override.

**Comment by cuongloveit** [comment]
me too. who can resolve this?

**Comment by jaisonoh** [comment]
The cause is Manifest merger failed. Simple way to solve the problem is just following the suggestion on console.

Add below code into application tag in AndroidManifest.xml   
```xml
tools:replace="android:theme" 
```

For example,
```xml
<application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme"
        tools:replace="android:theme">
```

**Comment by cuongloveit** [comment]
tks! the issue is resolved.

**Comment by boxme** [comment]
Thanks @jaisonoh !
