### ISSUE TITLE
No Callback at all?

### ISSUE THREAD

**Issue by aljlue** [boxme/SquareCamera#54]
Question: Is this a dummy project / does it need to be extended to work, because I get no callbacks.

So, describing the problem:

I tried to use this inside a project of mine and I get no callbacks at all.
Logcat / Console puts out this, when I click the checkmark after taking a picture: 

V/FA: Activity paused, time: 4408130
V/FA: Activity resumed, time: 4408198

A callback is not happening at all, I log every call of onActivityResult in my Activity.
Then I looked inside the code of the EditSavePhotoFragment and found this snippet

`view.findViewById(R.id.save_photo).setOnClickListener(new View.OnClickListener() {`
`@Override`
`public void onClick(View v) {`
`savePicture();`
`}`
`});`

This should save the picture, but the savePicture method is just a dummy for requesting the permissions, see here:

`private void savePicture() {`
`requestForPermission();`
`}`
`private void requestForPermission() {`
`RuntimePermissionActivity.startActivity(EditSavePhotoFragment.this,`
`REQUEST_STORAGE,`
`Manifest.permission.WRITE_EXTERNAL_STORAGE);`
`}`

So where exactly should the callback happen. Please give me a hint on how to fix this. Any help is very much appreciated!

**Comment by bmbariah** [comment]
SavePicture() calls requestForPermission() which if sucessfull calls public void onActivityResult(int requestCode, int resultCode, Intent data) that saves the image...you can launch a toast here to show image saved or other stuff

**Comment by aljlue** [comment]
worked fine indeed, thanks!
