### ISSUE TITLE
Manifest

### ISSUE THREAD

**Issue by GaneshShetty951** [boxme/SquareCamera#66]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@theme value=(@style/AppTheme) from AndroidManifest.xml:23:9-40
  	is also present at [com.github.boxme:squarecamera:1.1.0] AndroidManifest.xml:11:18-76 value=(@style/squarecamera__CameraFullScreenTheme).
  	Suggestion: add 'tools:replace="android:theme"' to <application> element at AndroidManifest.xml:17:5-180:19 to override.

**Comment by given8** [comment]
In the application tag in your xml file put this in: xlmns:replace="android:theme" then it should work.

**Comment by HayTran** [comment]
have same issue , I fix it like this by adding xmlns:tools="http://schemas.android.com/tools" to the top of mainfest file , and add tools:replace="android:theme" to be look like 
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"  // add tools line here 
    package="yourpackage">


    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme"
        tools:replace="android:theme"
