### ISSUE TITLE
data.getData() in  onActivityResult(int requestCode, int resultCode, Intent data)  is null

### ISSUE THREAD

**Issue by rorlig** [boxme/SquareCamera#9]
@Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        Log.d("on result:", "onActivityResult:" + resultCode + " request:" + requestCode  + " data " + data.getData() );
 }

data.getData() is null on Samsung Devices...

**Comment by philipgiuliani** [comment]
I found a maybe related issue on StackOverflow. http://stackoverflow.com/questions/4989010/android-samsung-camera-app-wont-return-intent-getdata

**Comment by rorlig** [comment]
I think the problem is probably here 

 File mediaStorageDir = new File(
                Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES),
                context.getString(R.string.app_name)
        );

        Log.d(TAG, "mediaDirectory " + mediaStorageDir.getAbsolutePath());

        if (!mediaStorageDir.exists()) {
            Log.d(TAG,"mediaStoreDirectory does not exist");
            if (!mediaStorageDir.mkdirs()) {
                Log.d(TAG,"mediaStorageDir cannot be created");
                return null;
            }
        }


I am getting mediaStorageDirectory cannot be created on the S5. Will do more digging.

**Comment by rorlig** [comment]
actually my bad. I didn't have the     
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

in the manifest

**Comment by sumbulkhan17** [comment]
> actually my bad. I didn't have the WRITE_EXTERNAL_STORAGE permission in the manifest

hey, i have already set the permission for WRITE_EXTERNAL_STORAGE in my manifest, but still the problem persists, can u help? my device is also samsung.. anyone please help
